# Generated by Django 6.0.4 on 2026-04-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('course_title', models.CharField(max_length=255)),
                ('student_image', models.ImageField(null=True, upload_to='certificates/images/')),
                ('project_link', models.URLField(blank=True, null=True)),
                ('certificate_file', models.FileField(null=True, upload_to='certificates/files/')),
            ],
        ),
    ]
