# Generated by Django 6.0.4 on 2026-04-14 07:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerificates', '0002_remove_certificate_id_certificate_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='student_id',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('revoked', 'Revoked')], default='valid', max_length=10),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/files/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course_title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/images/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student_name',
            field=models.CharField(max_length=200),
        ),
    ]
