# Generated by Django 6.0.4 on 2026-04-14 07:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerificates', '0003_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
